### ISSUE TITLE
Maximum stack size exceeded

### ISSUE THREAD

**Issue by dszakallas** [ForbesLindesay/spawn-sync#43]
I get this error on v0.10:

```
/Users/david/.../node_modules/spawn-sync/lib/json-buffer/index.js:39
    return JSON.stringify(/^:/.test(o) ? ':' + o : o)
                               ^
RangeError: Maximum call stack size exceeded
```

**UPDATE**

Only happens when stdout/err is inherited:

``` js
spawnSync(process.argv[0], process.argv.slice(1), { stdio: ['ignore', process.stdout, process.stderr] })
```

I did this workaround to avoid buffering on >= 0.12:

``` js
var spawnSync = require('child_process').spawnSync
var spawnSyncFallback = require('spawn-sync')
if (spawnSync) {
  spawnSync(process.argv[0], process.argv.slice(1),
    { stdio: ['ignore', process.stdout, 'ignore'] }
  )
} else {
  var res = spawnSyncFallback(process.argv[0], process.argv.slice(1),
    { stdio: ['ignore', 'pipe', 'ignore'] }
  )
  process.stdout.write(res.stdout) // very buffering
}
```

**Comment by szdavid92** [comment]
happens when I configure `stdio` to inherit parent configuration

```js
spawnSync(process.argv[0], process.argv.slice(1), { stdio: ['ignore', process.stdout, process.stderr] })
```

**Comment by szdavid92** [comment]
if I pipe it I get
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```

**Comment by ForbesLindesay** [comment]
You could try explicitly passing the string `'inherit'` rather than `process.stdout`.  I strongly suspect that would work fine.

**Comment by ForbesLindesay** [comment]
The latest version is just a stub with no postinstall script. It does require upgrading to a recent version of node.js
